version: '3'
services:

  kvrocks:
    image: apache/kvrocks
    working_dir: /kvrocks
    volumes:
        - ./storage:/var/lib/kvrocks
    command: ["--log-dir", "stdout"]
    healthcheck:
      test: ["CMD", "redis-cli", "-h", "127.0.0.1", "-p", "6101", "ping"]
      interval: 10s
      timeout: 1s
      retries: 3
      start_period: 30s
      start_interval: 10s

  redis:
    image: redis:7
    working_dir: /cache
    command: ./cache.conf --daemonize no
    volumes:
        - ./cache:/cache
    healthcheck:
      test: ["CMD", "redis-cli", "-s", "/cache/cache.sock", "ping"]
      interval: 10s
      timeout: 1s
      retries: 3
      start_period: 10s
      start_interval: 10s

  clamav:
    image: clamav/clamav
    volumes:
        - clamav-socket:/tmp
    healthcheck:
      test: ["CMD", "clamdscan", "--config=/etc/clamav/clamd.conf", "--ping", "1"]
      interval: 10s
      timeout: 1s
      retries: 3
      start_period: 120s
      start_interval: 10s

  pandora:
    build: .
    working_dir: /pandora
    tty: true
    command:
        - /bin/sh
        - -c
        - |
            sleep 60
            poetry run start
            tail -F ./LICENSE
    volumes:
        - ./cache:/pandora/cache
        - ./storage:/pandora/storage
        - ./pandora/workers:/pandora/pandora/workers
        - ./config:/pandora/config
        - ./yara_rules:/pandora/yara_rules
        - ./yara_repos:/pandora/yara_repos
        - ./logs:/pandora/logs
        - ./web_logs:/pandora/website/logs
        - ./tasks:/pandora/tasks
        - clamav-socket:/var/run/clamav
    links:
        - "clamav"
        - "redis"
        - "kvrocks"
    ports:
        - 6100:6100

volumes:
    clamav-socket:
